### ISSUE TITLE
Empty backend-Module

### ISSUE THREAD

**Issue by chricken** [uoziod/shop_manager#1]
Hi,
when I have installaed shop_manager, the backend-module stays empty.
I use Typo3 6.2, tt_products 2.7.14.

Is that a known issue?

Regards
Chricken

**Comment by uoziod** [comment]
There could be many different reasons. To catch it up, could you please also provide php-error? Error reporting often could be enabled with .htaccess, but you can also take a look on web-server error logs.

**Comment by chricken** [comment]
Thank you for your reply.
Error:
[13-Apr-2015 13:23:59 Europe/Berlin] PHP Fatal error: require_once(): Failed opening required 'PATH_t3libclass.t3lib_scbase.php' (include_path='/www/htdocs/w012bb07/inselweine/typo3/contrib/pear/:.:/usr/share/php:..') in /www/htdocs/w012bb07/inselweine/typo3conf/ext/shop_manager/mod1/index.php on line 31

Could that be an issue, because I use Version 6.2?

**Comment by mschulte63** [comment]
Hello,

I had the same problem with the Shop Manager.
The solution for this problem is to uncomment the line 31 with the require once statement in the file /var/www/web0/html/typo3conf/ext/shop_manager/mod1/index.php
With Typo Version 6.2 this mechanism was changed and the lib will be found automatically.

I Hope, that I  could help to solve this problem.

Best regards

Michael

**Comment by uoziod** [comment]
Fixed in 1.0.7
